server:
  port: 8888
spring:
  servlet:
    multipart:
      # 单个文件最大值
      max-file-size: 1024MB
      # 多个文件最大值
      max-request-size: 1024MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sbtest
    username: root
    password: abcDEF123___
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    local-date-time-format: yyyy-MM-dd HH:mm:ss
    local-date-format: yyyy-MM-dd
    local-time-format: HH:mm:ss
